# Generated by Django 6.0.2 on 2026-03-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='age',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='students',
            name='deparment',
            field=models.TextField(null=True),
        ),
    ]
