# Generated by Django 6.0.2 on 2026-03-03 23:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_students_email_students_gender_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.AddField(
            model_name='students',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='firstname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='lastname',
            field=models.CharField(max_length=30),
        ),
    ]
