# Generated by Django 6.0.2 on 2026-03-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_delete_faculty_students_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='deparment',
        ),
        migrations.AddField(
            model_name='students',
            name='department',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
