# Generated by Django 6.0.2 on 2026-04-08 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Signup',
        ),
    ]
